tools: add explicit include of the libgen.h header file
Compilation on MacOS fails with missing declaration of basename() function.
The function is declared in the same header file on Linux distributons
as well, thus the include is added unconditionally.

cc  -I/Users/jsuchane/work/virt-lint/target/aarch64-apple-darwin/debug/include/virt_lint -I/opt/homebrew/Cellar/libvirt/10.8.0/include -L/Users/jsuchane/work/virt-lint/target/aarch64-apple-darwin/debug -L/opt/homebrew/Cellar/libvirt/10.8.0/lib -lvirt_lint -lvirt virt-lint.c -o virt-lint
virt-lint.c:186:12: error: call to undeclared function 'basename'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  186 |     base = basename(progname_dup);
      |            ^
virt-lint.c:186:10: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
  186 |     base = basename(progname_dup);
      |          ^ ~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[1]: *** [virt-lint] Error 1

Signed-off-by: Jaroslav Suchanek <jsuchane@redhat.com>